# Generated by Django 4.2.4 on 2023-08-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='failure',
            options={'verbose_name': 'Узел отказа', 'verbose_name_plural': 'Узлы отказа'},
        ),
    ]
